[package]
name = "outfit_core"
version = "0.1.0"
edition = "2021"

[package.metadata.skyline]
titleid = "01006A800016E000"

[dependencies]
skyline = { git = "https://github.com/ultimate-research/skyline-rs", version="0.6.0" }
unity = { version = "0.3.0", git = "https://github.com/triabolicals/unity", branch = "macro" }
engage = { git = "https://github.com/triabolicals/engage", branch = "macro" }
bitflags = "2.11.0"

engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", features = [
    "app-assettable", "app-assettable-types", "app-chapterdata", "app-gmapsequence", "app-unitinfo", "app-unitinfo-types", "app-hubsequence", "app-gmapsequence-types",
    "app-structdata_1", "app-structbase", "app-gamevariable", "app-gameicon", "app-unitpool",
    "app-unit", "app-unit-types", "app-random_2", "app-basicmenu", "app-basicmenucontent", "app-basicmenuselect", "app-accessoryshopchangerootproc",
    "app-persondata", "app-jobdata", "app-itemdata", "app-goddata", "app-godunit",
    "app-gameuserdata", "app-singletonclass_1", "app-stream_2",
    "app-resourcemanager_2", "app-skillarray", "app-skillarray-types",
    "system-collections-generic-dictionary_2", "system-collections-generic-list_1",
    "combat-character", "combat-characterappearance", "combat-characterbuilder",
    "app-gmapmapinfocontent", "app-hubminimap", "app-rendermanager", "app-hubplayercontroller", "app-hublocatorgroup", "app-accessoryshopchangemenu-types",
    "app-singletonclass_1-types", "app-singletonprocinst_1", "app-singletonprocinst_1-types",
    "app-shopunitselectmenuitem", "app-shopunitselectmenucontent", "app-shopunitselectmenuitemcontent",
    "unity_engine", "app-fade", "app-procdesc", "app-procdesc-types", "app-fade-types", "app-proc", "app-procvoidfunction", "app-procvoidmethod", "app-procboolmethod",
    "app-accessoryshopchangeroot", "app-accessoryshopchangemenu", "app-hubaccessoryroom", "app-hubaccessoryshopsequence", "app-hubaccessoryroomcamera",
    "tm_pro-textmeshpro", "app-accessorymenuitem", "app-accessorymenuitemcontent", "app-accessoryequipmentinfo", "app-facethumbnail", "app-godpool", "app-singletonpool_2",
    "app-unitfor", "app-accessorydetailinfowindow", "combat-kaneko", "system-object", "app-backgroundmanager", "app-unitstatus",
    "app-sortiesequenceunitselect", "app-unitinfocharaimagemaskoffset", "app-unitinfowindowcharamodel",
    "app-singletonmonobehaviour_1", "app-singletonmonobehaviourlist_1", "app-unitselectmenu", "app-mapmind", "app-mess", "app-gamemessage",
    "app-unitutil", "combat-proportionparameters", "combat-characterjoint", "combat-dressutility", "combat-characterasset", "combat-characterassett_1",
    "combat-characterproportion", "app-talk3_d-characterfactoryasync_2", "app-unitinfowindowcharamodel-types",
    "system-action", "app-unitinfowindowcharaupdater", "app-bitstruct", "app-unitaccessory", "app-unitaccessorylist", "app-accessorydata", "app-pad", "app-sortieutil",
    "app-titlebar", "app-ut", "app-yesmenuitem", "app-basicdialogitemyes", "app-basicdialog",
    "app-photographsequence", "app-photographeditdisposmenu", "app-photographcameracontroller", "app-photographdisposinfo", "app-photographtopsequence",
    "combat-characterfactoryasync", "app-photographpausedata", "app-gameuserdata-types",
    "root_motion-final_ik-lookatik",
] }
unity2 = { git = "https://github.com/DivineDragonFanClub/unity2"}

[patch."https://github.com/triabolicals/engage"]
engage = {path = "/Users/trile/Project/lib/engage"}

[patch."https://github.com/triabolicals/unity"]
unity = {path = "/Users/trile/Project/lib2/unity"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 2